import { useEffect, useState } from "react";
import { ArrowLeft, BrainCircuit, Loader2, RotateCcw, Save, Zap } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { api, errorMessage } from "@/lib/api";
import type { ModelInfo, ModelSettings } from "@/lib/types";

type Tier = keyof ModelSettings;

const TIERS: Record<Tier, { title: string; blurb: string; icon: React.ReactNode }> = {
  smart: {
    title: "Розумна модель",
    blurb:
      "Генерація конспектів, перевірка письмових відповідей і підказки. Викликається рідко, результат зберігається на диску — тут варто платити за якість.",
    icon: <BrainCircuit className="size-5 text-primary" />,
  },
  fast: {
    title: "Швидка модель",
    blurb:
      "Питання для сесій і тести. Викликається постійно, тому має бути дешевою та швидкою.",
    icon: <Zap className="size-5 text-chart-3" />,
  },
};

/**
 * Which model each tier resolves to.
 *
 * The tier a job runs at is not settable and never will be — a knowledge note generated by
 * the cheap model is worth less than no note, and a quiz generated by the expensive one
 * costs more than the whole session. What is settable is which model each tier *names*,
 * which is how Claude, Gemini and anything else `agy` lists all become reachable.
 */
export function SettingsScreen({ onBack }: { onBack: () => void }) {
  const [chosen, setChosen] = useState<ModelSettings | null>(null);
  const [defaults, setDefaults] = useState<ModelSettings | null>(null);
  const [available, setAvailable] = useState<ModelInfo[] | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    api
      .getModels()
      .then((choice) => {
        setChosen(choice.models);
        setDefaults(choice.defaults);
      })
      .catch((error) => toast.error(errorMessage(error)));

    // Best effort: the list needs the CLI, and not having it must not stop the ids being
    // edited by hand.
    api
      .listModels()
      .then(setAvailable)
      .catch(() => setAvailable([]));
  }, []);

  async function save() {
    if (!chosen) return;
    setSaving(true);
    try {
      const choice = await api.setModels(chosen);
      setChosen(choice.models);
      toast.success("Моделі збережено");
    } catch (error) {
      toast.error(errorMessage(error));
    } finally {
      setSaving(false);
    }
  }

  if (!chosen || !defaults) {
    return (
      <div className="flex items-center justify-center gap-2 p-16 text-sm text-muted-foreground">
        <Loader2 className="size-4 animate-spin" />
        Завантаження…
      </div>
    );
  }

  const dirty = defaults.smart !== chosen.smart || defaults.fast !== chosen.fast;

  return (
    <div className="mx-auto w-full max-w-3xl space-y-6 p-8">
      <div className="space-y-3">
        <Button variant="ghost" size="sm" onClick={onBack} className="-ml-2">
          <ArrowLeft className="size-4" />
          Назад
        </Button>
        <h1 className="text-2xl font-semibold tracking-tight">Моделі</h1>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Кожне завдання назавжди закріплене за своїм рівнем — конспекти й підказки за
          розумним, тести й сесії за швидким. Обрати можна лише те, яка саме модель стоїть за
          кожним рівнем.
        </p>
      </div>

      {(["smart", "fast"] as const).map((tier) => (
        <Card key={tier}>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              {TIERS[tier].icon}
              {TIERS[tier].title}
            </CardTitle>
            <CardDescription className="leading-relaxed">{TIERS[tier].blurb}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {available === null ? (
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="size-4 animate-spin" />
                Питаємо в `agy`, які моделі доступні…
              </div>
            ) : available.length > 0 ? (
              <Select
                value={chosen[tier]}
                // base-ui hands back `null` when a selection is cleared; the tier always
                // needs an id, so that is simply ignored.
                onValueChange={(value) =>
                  typeof value === "string" ? setChosen({ ...chosen, [tier]: value }) : undefined
                }
              >
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {available.map((model) => (
                    <SelectItem key={model.id} value={model.id}>
                      {model.label || model.id}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : null}

            <div className="space-y-1.5">
              <p className="text-xs text-muted-foreground">
                {available && available.length === 0
                  ? "Список моделей отримати не вдалося — введіть ідентифікатор вручну."
                  : "Або впишіть ідентифікатор вручну:"}
              </p>
              <Input
                value={chosen[tier]}
                spellCheck={false}
                className="font-mono text-xs"
                onChange={(event) => {
                  // Read before the update: React nulls `currentTarget` once the handler
                  // returns, and a functional updater would run later, during render.
                  const value = event.target.value;
                  setChosen((current) => (current ? { ...current, [tier]: value } : current));
                }}
              />
            </div>
          </CardContent>
        </Card>
      ))}

      <div className="flex flex-wrap items-center gap-3 border-t border-border pt-4">
        <Button onClick={save} disabled={saving}>
          {saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}
          Зберегти
        </Button>
        {dirty ? (
          <Button variant="ghost" onClick={() => setChosen(defaults)} disabled={saving}>
            <RotateCcw className="size-4" />
            Повернути стандартні
          </Button>
        ) : null}
      </div>
    </div>
  );
}
